version: "3"
services:

  group_0_node_0:
    build:
     context: .
    environment:
     - GROUP_ID=0
     - LOCAL_NODE_ID=0
     - GLOBAL_NODE_ID=0
     - DEV=1
    networks:
#     - group_0_local_net
     - group_global_net
  group_0_node_1:
    build:
     context: .
    environment:
     - GROUP_ID=0
     - LOCAL_NODE_ID=1
     - GLOBAL_NODE_ID=1
     - DEV=1
    networks:
#     - group_0_local_net
     - group_global_net
  group_0_node_2:
    build:
     context: .
    environment:
     - GROUP_ID=0
     - LOCAL_NODE_ID=2
     - GLOBAL_NODE_ID=2
     - DEV=1
    networks:
#     - group_0_local_net
     - group_global_net
  group_0_node_3:
    build:
     context: .
    environment:
     - GROUP_ID=0
     - LOCAL_NODE_ID=3
     - GLOBAL_NODE_ID=3
     - DEV=1
    networks:
#     - group_0_local_net
     - group_global_net
  group_1_node_0:
    build:
     context: .
    environment:
     - GROUP_ID=1
     - LOCAL_NODE_ID=0
     - GLOBAL_NODE_ID=4
     - DEV=1
    networks:
#     - group_1_local_net
     - group_global_net
  group_1_node_1:
    build:
     context: .
    environment:
     - GROUP_ID=1
     - LOCAL_NODE_ID=1
     - GLOBAL_NODE_ID=5
     - DEV=1
    networks:
#     - group_1_local_net
     - group_global_net
  group_1_node_2:
    build:
     context: .
    environment:
     - GROUP_ID=1
     - LOCAL_NODE_ID=2
     - GLOBAL_NODE_ID=6
     - DEV=1
    networks:
#     - group_1_local_net
     - group_global_net
  group_1_node_3:
    build:
     context: .
    environment:
     - GROUP_ID=1
     - LOCAL_NODE_ID=3
     - GLOBAL_NODE_ID=7
     - DEV=1
    networks:
#     - group_1_local_net
     - group_global_net
  group_2_node_0:
    build:
     context: .
    environment:
     - GROUP_ID=2
     - LOCAL_NODE_ID=0
     - GLOBAL_NODE_ID=8
     - DEV=1
    networks:
#     - group_2_local_net
     - group_global_net
  group_2_node_1:
    build:
     context: .
    environment:
     - GROUP_ID=2
     - LOCAL_NODE_ID=1
     - GLOBAL_NODE_ID=9
     - DEV=1
    networks:
#     - group_2_local_net
     - group_global_net
  group_2_node_2:
    build:
     context: .
    environment:
     - GROUP_ID=2
     - LOCAL_NODE_ID=2
     - GLOBAL_NODE_ID=10
     - DEV=1
    networks:
#     - group_2_local_net
     - group_global_net
  group_2_node_3:
    build:
     context: .
    environment:
     - GROUP_ID=2
     - LOCAL_NODE_ID=3
     - GLOBAL_NODE_ID=11
     - DEV=1
    networks:
#     - group_2_local_net
     - group_global_net
  group_3_node_0:
    build:
     context: .
    environment:
     - GROUP_ID=3
     - LOCAL_NODE_ID=0
     - GLOBAL_NODE_ID=9
     - DEV=1
    networks:
#     - group_3_local_net
     - group_global_net
  group_3_node_1:
    build:
     context: .
    environment:
     - GROUP_ID=3
     - LOCAL_NODE_ID=1
     - GLOBAL_NODE_ID=10
     - DEV=1
    networks:
#     - group_3_local_net
     - group_global_net
  group_3_node_2:
    build:
     context: .
    environment:
     - GROUP_ID=3
     - LOCAL_NODE_ID=2
     - GLOBAL_NODE_ID=11
     - DEV=1
    networks:
#     - group_3_local_net
     - group_global_net
  group_3_node_3:
    build:
     context: .
    environment:
     - GROUP_ID=3
     - LOCAL_NODE_ID=3
     - GLOBAL_NODE_ID=12
     - DEV=1
    networks:
#     - group_3_local_net
     - group_global_net
  group_1_proxy_0:
    hostname: proxy
    build:
     context: .
     dockerfile: Dockerfile.proxy
    environment:
     - GROUP_ID=1
     - DEV=1
    networks:
     - group_global_net

networks:
#  group_0_local_net:
#    driver: macvlan
#  group_1_local_net:
#    driver: macvlan
#  group_2_local_net:
#    driver: macvlan
#  group_3_local_net:
#    driver: macvlan
  group_global_net:
    driver: macvlan
