version: '3'
services:
 group_0_proxy_0:
  build:
   context: .
   dockerfile: Dockerfile.proxy
  environment:
   - GROUP_ID=0
  network_mode: "host"

 group_1_proxy_0:
  build:
   context: .
   dockerfile: Dockerfile.proxy
  environment:
   - GROUP_ID=1
  network_mode: "host"

 group_2_proxy_0:
  build:
   context: .
   dockerfile: Dockerfile.proxy
  environment:
   - GROUP_ID=2
  network_mode: "host"